baseURL: "https://coldbottle.github.io/"
title: coldbottle
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: Categories
          url: categories/
          weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "ExampleSite description"
  author: coldbottle

  defaultTheme: auto # dark, light
  # disableThemeToggle: false
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: false
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowToc: true


  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    # imageWidth: 120
    # imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there"
    Content: >
      Welcome to my blog

  #analytics:
  #    google:
  #        SiteVerificationTag: "XYZabc"

  #cover:
  #    hidden: true # hide everywhere but not in structured data
  #    hiddenInList: true # hide on list pages and home
  #    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  #fuseOpts:
  #    isCaseSensitive: false
  #    shouldSort: true
  #    location: 0
  #    distance: 1000
  #    threshold: 0.4
  #    minMatchCharLength: 0
  #    keys: ["title", "permalink", "summary", "content"]
taxonomies:
  category: categories
  tag: tags
  series: series
#menu:
#    main:
#        - identifier: categories
#          name: categories
#          url: /categories/
#          weight: 10
#        - identifier: tags
#          name: tags
#          url: /tags/
#          weight: 20
#        - identifier: example
#          name: example.org
#          url: https://example.org
#          weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
